### ISSUE TITLE
Buggy interaction between default gestures and Multitouch, M2 Air, 12.5.1

### ISSUE THREAD

**Issue by dfsnow** [rxhanson/Multitouch-Community#123]
# Problem

I'm seeing very buggy interactions between Multitouch and Mac's default trackpad gestures. The basic issue is:

1. Default gestures work fine / as expected
2. Multitouch _barely_ works when default gestures are disabled. Registers maybe 1 in 10 swipes
3. Multitouch works well when _default gestures also enabled_. Sensitivity is as expected. However, default gestures interfere with Multitouch actions

Here's my debug log:

```
Multitouch: 1.27.6 (161)
macOS: Version 12.5.1 (Build 21G83)
Model: Mac14,2
Devices: ["internalTrackpad2:161:161"]
Multitouch Configuration: [{"gid":{"gesture":"threeTap","appId":""},"r":{"type":3,"action":300}},{"gid":{"gesture":"threeTap","appId":"com.apple.Safari"},"r":{"type":3,"action":301}},{"gid":{"gesture":"threeSwipeUp","appId":""},"r":{"type":5,"action":504,"flag":true}},{"gid":{"gesture":"threeSwipeDown","appId":""},"r":{"type":5,"action":505,"flag":true}},{"gid":{"gesture":"threeSwipeLeft","appId":""},"r":{"type":5,"action":501,"flag":true}},{"gid":{"gesture":"threeSwipeRight","appId":""},"r":{"type":5,"action":500,"flag":true}}] | tap-to-click
```

My basic gestures are:

- Three finger tap for middle click
- Three finger swipe to swap tabs, open new ones (up), and close tabs (down)

I've tried changing the following, with no improvements:

- Private framework
- Restart on wake
- All sensitivity settings

## 1. Default gestures (no Multitouch)

Settings are:

<img width="654" alt="Screen Shot 2022-08-19 at 12 38 40 PM" src="https://user-images.githubusercontent.com/31494343/185679015-85367ae9-56a2-4a93-b0be-ca0b4fb3814c.png">

Here's a screencast: 

https://user-images.githubusercontent.com/31494343/185679051-b927d42c-e1d9-431b-9380-ae57f16314af.mov

### Notes:

- When "Swipe between full-screen apps" is set to four fingers, swiping with three fingers in Safari is treated as "back" and "forward", but without the animation of two finger swipes

## 2. Multitouch only (all defaults disabled)

Trackpad settings:

<img width="640" alt="Screen Shot 2022-08-19 at 1 01 23 PM" src="https://user-images.githubusercontent.com/31494343/185679869-0f619fb1-cd65-4100-b313-0971d64c423c.png">

Multitouch settings:

<img width="561" alt="Screen Shot 2022-08-19 at 1 01 50 PM" src="https://user-images.githubusercontent.com/31494343/185679895-de7b85b4-7f05-4948-a96d-b8504ba9e926.png">

Screen recording:

https://user-images.githubusercontent.com/31494343/185680726-7eba8c01-e9d4-409d-b77c-2a6b88816996.mov

## 3. Multitouch + default gestures enabled

Trackpad settings:

<img width="637" alt="Screen Shot 2022-08-19 at 1 14 24 PM" src="https://user-images.githubusercontent.com/31494343/185681769-4865daab-53b0-4a03-93ae-9ca7d50628a9.png">

Multitouch settings:

<img width="556" alt="Screen Shot 2022-08-19 at 1 14 37 PM" src="https://user-images.githubusercontent.com/31494343/185681806-f5fbb9ad-f2d4-47fc-9bff-a8caff8b24a3.png">

Screen recording:

https://user-images.githubusercontent.com/31494343/185681868-64833e29-43b9-418b-84fe-2af47664d412.mov

### Notes:

- Multitouch gestures work great **if** three finger "Swipe between full-screen apps" is also set to three-fingers
- If "Swipe between full-screen apps" is set to four fingers, Multitouch sensitivity plummets to the point of being unusable
- When "Swipe between full-screen apps" is set to three fingers, Multitouch gestures are enabled, AND a full-screen app is open, then a three finger swipe will change tabs AND swap to the full-screen app

# Expected behavior

I would expect Multitouch to work as well as it does at the beginning of screencast 3, but without needing default gestures to be enabled OR for Multitouch to work with defaults enabled but "Swipe between full-screen apps" set to four fingers (instead of three), as in the very last part of screencast 3.

**Comment by rxhanson** [comment]
Really sorry for the delayed response here. I was never able to reproduce your experience, and your expected behavior is what I experience. Nobody else has reported this to me, and this is a fairly common configuration - which does unfortunately point to something strange specific to your Mac. I'll be honest, this doesn't strike me as something easy to figure out, and it would take some serious back and forth debug time to chip away at it with a low potential for a solution. Since this is obviously not a good experience, I took forever to respond, and I don't see a fix near on the horizon, if you'd like a refund or any of my other apps for free, then just send me an email.

**Comment by dfsnow** [comment]
No worries on the delay, I appreciate you taking the time. Even with the bugginess Multitouch still works well enough for me to continue to use it, so no refund necessary.

If you do see more reports of this issue in the future, I'm happy to do some in-depth debugging. For now, closing this issue.
