### ISSUE TITLE
"Force touch one: top/bottom right corner" triggers 5 to 7 times when assigned with Bash command.

### ISSUE THREAD

**Issue by upstroke-version** [rxhanson/Multitouch-Community#129]
"Force touch one: top/bottom right corner" triggers 5 to 7 times when assigned with "Execute/Bash command".
Again, this only happens on top and bottom **RIGHT**  when assigned to Execute/Bash command, which was very weird and oddly specific.

This is when assigned to other tasks like volum up
> 2022-10-03T00:21:54+09:00: Gesture matched: oneForceBottomRight

This is when assigned with bash command
> 2022-10-03T00:24:17+09:00: Gesture matched: oneForceBottomRight
2022-10-03T00:24:17+09:00: Gesture matched: oneForceBottomRight
2022-10-03T00:24:17+09:00: Gesture matched: oneForceBottomRight
2022-10-03T00:24:17+09:00: Gesture matched: oneForceBottomRight
2022-10-03T00:24:17+09:00: Gesture matched: oneForceBottomRight

FYI,the Bash command was this, if that even matters.
> shortcuts run "Shortcuts name here"

I was really confused when Shortcuts that worked with keyboard shortcut threw error when used with trackpad gesture...
Now at least I know the cause, I hope you would be able to find the root cause of the bug and fix it.

**Comment by rxhanson** [comment]
Thanks for reporting. I can reproduce this so I should be able to push out a fix for it in the next release.

**Comment by rxhanson** [comment]
Fix is in, and I'll post back when the next release is out.

**Comment by upstroke-version** [comment]
Thanks for quick fix!
