### ISSUE TITLE
Cmd+Click emulation on ForceClick doesn't work in VSCode and Intellij

### ISSUE THREAD

**Issue by ris58h** [rxhanson/Multitouch-Community#130]
Probably it's an issue with VSCode and not Multitouch but could you confirm that?
In Firefox it works as expected btw (opens link in a new tab).
UPDATE:
It doesn't work in Intellij IDEA either.

**Comment by rxhanson** [comment]
This is a side effect of force clicking, unfortunately. Because there is an initial down click before for the force touch, apps like Vscode and IntelliJ will not respond to the additional click in the programmatic cmd click. I'm not aware of a good way around that at this time.
