### ISSUE TITLE
About export gesture settings.

### ISSUE THREAD

**Issue by kuper0201** [rxhanson/Multitouch-Community#144]
Can you add the ability to export the setting files from the gestures you set.
ex) plist, json
Manually setting up the gestures after a clean OS installation or moving it to another new device is terrible!
I am sorry to my bad english.

**Comment by kuper0201** [comment]
> 내 계획은 가져오기/내보내기 구성 버튼을 갖는 것입니다.
> 
> 제스처는 iCloud를 통해 동기화되지만 plist의 세부 정보는 다음과 같습니다. https://github.com/rxhanson/Multitouch-Community/wiki/Transferring-Multitouch-Settings-to-a-Different-Mac

Thanks for your quick response!
Now i know how to backup my setting.
I'm using the app very useful.
Thank you for develop this app.

**Comment by kuper0201** [comment]
> 내 계획은 가져오기/내보내기 구성 버튼을 갖는 것입니다.
> 
> 제스처는 iCloud를 통해 동기화되지만 plist의 세부 정보는 다음과 같습니다. https://github.com/rxhanson/Multitouch-Community/wiki/Transferring-Multitouch-Settings-to-a-Different-Mac

Hi again!
I copied the plist file to desktop for testing and deleted all gestures.
And i kill the multitouch app by killall command to restore plist file.
When i re-paste the copied plist file, the multitouch app does not show anything.

**Comment by rxhanson** [comment]
Try logging out and logging back in. macOS will cache the plists and might not refresh the cache on its own.

**Comment by kuper0201** [comment]
> 

It's the same problem after logout or reboot.

**Comment by rxhanson** [comment]
Ok, I think I see the right way to do this:

1. Quit Multitouch
2. Put the desired plist in ~/Library/Preferences
3. Run `defaults read com.brassmonkery.Multitouch.plist` in Terminal
4. Open Multitouch

Does that work for you? I think the cache was overwritten by an empty plist, and that was the problem. Running the defaults read command should properly set the cache.

(I need to just make the export/import buttons).

**Comment by rxhanson** [comment]
Thanks for troubleshooting with me. I updated the instructions on the wiki page with this information.
