### ISSUE TITLE
Support for Orion as a Browser

### ISSUE THREAD

**Issue by sur4y** [rxhanson/Multitouch-Community#148]
Would it be possible to add gesture support for [Orion](https://browser.kagi.com)?

**Comment by rxhanson** [comment]
Ah, yes. I have been meaning to do this for a while and forgot to add it in on the previous release. It'll go in the next.

**Comment by sur4y** [comment]
Thank you so much! Is there an ETA for the upcoming release?

**Comment by rxhanson** [comment]
Here's a quick beta, let me know if you try it and have any issues.

https://www.multitouch.app/beta/multitouch1.27.12.dmg

**Comment by sur4y** [comment]
Apologies for the terribly late response, I am currently typing this in Orion and it works! Thank you so much!

**Comment by rxhanson** [comment]
Great, thanks for following up!
