### ISSUE TITLE
Click application in dock hides it

### ISSUE THREAD

**Issue by tlfzhylj** [rxhanson/Multitouch-Community#150]
Is it possible to use this tool to make option + click an application in the dock the default when only clicking the mouse without any keys pressed?

In other words, I want clicking an application in the dock to hide the application - just the way option + click does.

**Comment by rxhanson** [comment]
This is not possible with the current functionality. I'll give this some thought for a future update, though.

**Comment by rxhanson** [comment]
Great! I was thinking you wanted specifically to always execute option+click when the cursor was over a dock icon.

**Comment by tlfzhylj** [comment]
Ideally yes, but it's an ok approach. Can get used to it :-)

**Comment by tlfzhylj** [comment]
I also configured force touch to hide application under cursor. Very useful for my needs.
![image](https://user-images.githubusercontent.com/29739663/222076270-c878396d-a70e-4030-b28c-4b2ff55a72e5.png)

**Comment by tlfzhylj** [comment]
The issue may be closed. My needs are covered.
