### ISSUE TITLE
Window management not working across monitors

### ISSUE THREAD

**Issue by rgreuel** [rxhanson/Multitouch-Community#152]
Hey, the window management shortcuts aren't working across a multi-monitor set up. I was previously using Rectangle which allowed snapping windows across monitors. With Multitouch, I'm needing to manually move it to the other monitor before being able to snap it to edges on that monitor. Can this support be added? Thanks.

**Comment by rxhanson** [comment]
Thanks for reporting. I don't think I understand exactly the issue you are having. 

Is it that your keyboard shortcut for move to next display is not working? Or is it that when you drag a window to the next display, you have to release the drag on the next display and then drag it to the screen edge in order to snap it?

**Comment by rgreuel** [comment]
I didn't realize there's a separate keyboard shortcut to move to next display. I confirmed that works, however, it isn't necessary to use that shortcut in Rectange. For example, I can use the `Left Half` shortcut to snap to the left of my primary monitor, then another `Left Half` will take it to my monitor on the left. The behavior in Multitouch is different in that I can't get the window to the other monitor without using the prev/next display shortcuts.

**Comment by rxhanson** [comment]
This is fairly unintuitive in Multitouch, but you need to check the box in the Settings tab for 
"Window action repetitions". In the next release of Multitouch, I will be rolling in a lot of the recent changes from Rectangle and am planning on adjusting this. Let me know if you still have issues.

**Comment by rgreuel** [comment]
That fixed it for me. Thanks for pointing out that setting for me and for the support!
