### ISSUE TITLE
Unable to add shortcut based on alt or shift

### ISSUE THREAD

**Issue by andrewdotcallahan** [rxhanson/Multitouch-Community#163]
I started trialing Multitouch today (1.27.14), and am looking to port some existing BTT shortcuts over.

I observe that I cannot add Keyboard shortcuts that don't feature CMD or control. E.g. I cannot bind `alt+T` to open my terminal. I observe that `alt+cmd+T` /does/ work, but I'd like to be able to bind shortcuts with only alt.

**Comment by rxhanson** [comment]
I put a fix in for this in the latest version (1.27.16). You can update from within the app or at https://multitouch.app. Let me know if you try it and hit any issues.

**Comment by andrewdotcallahan** [comment]
Thank you - I see the behavior working correctly now!
