### ISSUE TITLE
Remap keyboard's eject button

### ISSUE THREAD

**Issue by tlfzhylj** [rxhanson/Multitouch-Community#168]
Hi.

Like described in this article: [How to Make Your Mac Keyboard's Eject Key Useful Again](https://www.howtogeek.com/413824/how-to-make-your-mac-keyboards-eject-key-useful-again/), it would be useful to remap the keyboard's eject button.

I can't find "Eject" under Key Remap in Multitouch, nor does anything happen when I try to record the key with keyboard shortcuts.

**Comment by rxhanson** [comment]
Here's the discussion on this one: https://github.com/rxhanson/Multitouch-Community/discussions/153#discussioncomment-5209770
