### ISSUE TITLE
Constant "Unable to listen to device input" error

### ISSUE THREAD

**Issue by Makishima** [rxhanson/Multitouch-Community#171]
Hello! 
After installing version 1.27.21 I get permanent "Unable to listen to device input" error. 
I have tried recommendation to revoke and grant permissions and even complete reinstall.

**Comment by rxhanson** [comment]
When you tried to revoke and grant permissions, did you do each of the following steps?
1. Quit Multitouch
2. Go to System Settings > Privacy & Security > Accessibility
3. Disable Multitouch
4. Remove Multitouch, using the minus button
5. Restart your Mac
6. Relaunch and re-add permissions as prompted

**Comment by Makishima** [comment]
> Remove Multitouch with the Minus Button

This helps, thanks.
Maybe add it to the message box?
