### ISSUE TITLE
[BUG] Can't record a system shortcut

### ISSUE THREAD

**Issue by Romachamp** [rxhanson/Multitouch-Community#211]
Version of **MultiTouch**: Multitouch v1.27.31 (186)
Version of **MacOS**: MacOS Sonoma
Detailed **description**: 1. Settings > Keyboard/Mouse 2. Plus icon(+) 3. New keyboard shortcut 4(Bug appears). When I try to record a system shortcut command + Q it just quits the app, and doesn't save it, when I record command + W, it stops the process of recording without saving the shortcut as well, command + H works good, but these 2 can't be recorded, because they just stop the process. 

Please, fix this behaviour
Thank you, in advance!

**Comment by rxhanson** [comment]
Thanks for the details, I'll take a look at this one for the next release.

**Comment by rxhanson** [comment]
Finally got around to giving this some more thought, and my current plan is to leave this as-is. For the most part, I view Multitouch as a way to add additional functionality to macOS instead of remapping system functionality. I'd be willing to reconsider with significant demand, though.
