### ISSUE TITLE
Feature request: add support native Mac OS Sequoia windows tiling

### ISSUE THREAD

**Issue by steeldimon** [rxhanson/Multitouch-Community#219]
In Mac OS 15.0 Sequoia apple added support for window native tiling, can you add this to multitouch app? For now we are have conflicts between tiling source from multitouch.app and Mac OS

**Comment by rxhanson** [comment]
Thanks for asking. Unfortunately, there is no public API for the native tiling in macOS 15, so you'll have to pick one or the other at this time.

(For reference, the macOS tiling settings are in System Settings -> Desktop & Dock -> Windows)
