### ISSUE TITLE
Three & Four finger swipe gestures can scroll

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/Multitouch-Community#54]
Ideally, these shouldn't scroll. Not everyone has this issue.

**Comment by nomantis** [comment]
Bumping this one! I experience this all the time and not sure what I can do to disable scrolling for three/four finger swipe gestures.

**Comment by rxhanson** [comment]
With the latest few versions of macOS and the way that Multitouch currently works, unfortunately there isn't a way to remove the scrolling. The only way to get a setup that avoids scrolling while still using Multitouch for swipe gestures is to configure a custom Multitouch gesture for 3 finger swipe but leave macOS 4 finger swipe behavior configured. It's possible that I could figure out a way around this at some point, but there are other items in my Multitouch backlog that have higher priority.

**Comment by krizajb** [comment]
Can you please provide an example for the workaround you mentioned. Thank you.

**Comment by rxhanson** [comment]
With a quick test, it looks like scrolling now happens, even with just four finger swipes configured in macOS. Right now, the only setup I'm seeing where scrolling doesn't happen is if you have swipe between full-screen applications set to three fingers, and Mission Control / App Exposé not set to three fingers. And then you're only left with three finger swipe up and down as something you could configure in Multitouch without scrolling :(

I'll give this another look.

**Comment by krizajb** [comment]
Oh, this is perfect for me it seems! I will keep on testing it today but so far it looks promising, thanks! :)
