### ISSUE TITLE
Double execution for a single gesture

### ISSUE THREAD

**Issue by gilbigdog** [rxhanson/Multitouch-Community#92]
Hi, I was waiting for app like Multitouch and  I cannot fully utilize macbook without it.

I registered "Rest One, swipe two down to the right" gesture with Action Browser "Close Tab".

About every 3~4th attempts, a signle gesture closes two tabs. I was trying to replicate constantly but no luck. I had used the same gesture with another touch app that no longer working without an issue.

**Comment by rxhanson** [comment]
Would you be able to do a screen recording of it? Or at least send logs? 

For the screen recording, it would help to have the logger and the touch viewer displayed. You can show both of those from Help->Debug in the menu.

**Comment by gilbigdog** [comment]
please have attached video of reproducing the issue with logger and touch viewers enabled.
https://user-images.githubusercontent.com/1994653/157609284-5bbced3e-34a5-41fa-80b0-c52998dbede5.mov

**Comment by rxhanson** [comment]
Thanks! looks like it is performing a duplicate execution of the gesture. I'll post back when a next version is ready.

**Comment by rxhanson** [comment]
Just realized I forgot to post back here. v1.27.3 did contain a fix for this. Have you noticed the same issue after having updated to it?

**Comment by gilbigdog** [comment]
Earlier I checked this ticket whether resolved or not and it wasn't(Should I close it as requester?). But I noticed that this issue doesn't happen since last update. Thanks for the FIx!
